org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric / Minecraft
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2
fabric_api_version=0.161.0+26.3
thirst_version=1.6.2+26.3
farmers_delight_version=26.3-3.6.27
more_delight_version=26.09.16-26.3-fabric
delight_lib_version=26.09.16-26.3-fabric
kaleidoscope_cookery_version=1.6.0.3-fabric+mc26.3
kaleidoscope_tavern_version=1.2.0.11-fabric+mc26.3

# Mod
mod_version=0.1.0-alpha.1
maven_group=com.davidblackcn
archives_name=buildup_vitals
